language: java
jdk:
  - openjdk11
script:
  - "./mvnw clean verify"
branches:
  only:
    - main
cache:
  directories:
    - $HOME/m2
deploy:
  provider: heroku
  api_key: $our_api_key
  app: moneytransferappactapi
  on:
    repo: Nahi-Terefe/moneytransfserapi.git
    branch: main
